language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t sdchhoker/docker-react .

script:
    - docker run -e CI=true sdchhoker/docker-react npm run test
